import type { ScambioUI } from './scambi-types';

export const MOCK_SCAMBI: ScambioUI[] = [
  {
    id: 'sc-1',
    numericId: 1,
    title: 'Black Lotus Alpha - Near Mint',
    image: 'https://picsum.photos/seed/blacklotus/400/560',
    seller: 'MarcoTCG',
    sellerCountry: 'IT',
    sellerRating: 99,
    sellerReviewCount: 124,
    game: 'mtg',
    description: 'Splendida Black Lotus Alpha in condizioni NM. Protego in doppio sleeve fin dall\'acquisto. Nessun graffio visibile, angoli perfetti.',
    imageFront: 'https://picsum.photos/seed/blacklotus/800/1120',
    imageBack: 'https://picsum.photos/seed/blacklotusb/800/1120',
    condition: 'Near Mint',
    createdByUserId: 'user-marco',
    wantsInReturn: 'Mox Pearl Beta + Mox Sapphire Beta',
  },
  {
    id: 'sc-2',
    numericId: 2,
    title: 'Charizard 1st Edition PSA 9',
    image: 'https://picsum.photos/seed/charizard/400/560',
    seller: 'GiuliaCards',
    sellerCountry: 'IT',
    sellerRating: 97,
    sellerReviewCount: 58,
    game: 'pokemon',
    description: 'Charizard Base Set 1st Edition, gradato PSA 9. Custodia originale PSA intatta.',
    imageFront: 'https://picsum.photos/seed/charizard/800/1120',
    imageBack: 'https://picsum.photos/seed/charizardb/800/1120',
    condition: 'Gradato PSA 9',
    createdByUserId: 'user-giulia',
    wantsInReturn: 'Blastoise 1st Edition PSA 9 o superiore',
  },
  {
    id: 'sc-3',
    numericId: 3,
    title: 'Shanks Secret Rare OP-05',
    image: 'https://picsum.photos/seed/shanksop/400/560',
    seller: 'LuffyTrader',
    sellerCountry: 'IT',
    sellerRating: 95,
    sellerReviewCount: 32,
    game: 'op',
    description: 'Shanks Secret Rare dalla serie OP-05. Appena pullata, messa subito in toploader.',
    imageFront: 'https://picsum.photos/seed/shanksop/800/1120',
    imageBack: 'https://picsum.photos/seed/shanksopb/800/1120',
    condition: 'Mint',
    createdByUserId: 'user-luffy',
    wantsInReturn: 'Monkey D. Luffy SP OP-04',
  },
  {
    id: 'sc-4',
    numericId: 4,
    title: 'Blue-Eyes White Dragon LOB-001',
    image: 'https://picsum.photos/seed/bewd/400/560',
    seller: 'YugiKing',
    sellerCountry: 'IT',
    sellerRating: 98,
    sellerReviewCount: 210,
    game: 'ygo',
    description: 'Blue-Eyes White Dragon LOB-001 1st Edition (NA). Lieve usura ai bordi, overall LP.',
    imageFront: 'https://picsum.photos/seed/bewd/800/1120',
    imageBack: 'https://picsum.photos/seed/bewdb/800/1120',
    condition: 'Lightly Played',
    createdByUserId: 'user-yugi',
    wantsInReturn: 'Dark Magician BPT o SDY-006 1st',
  },
  {
    id: 'sc-5',
    numericId: 5,
    title: 'Mickey Mouse Enchanted Lorcana',
    image: 'https://picsum.photos/seed/mickeylor/400/560',
    seller: 'DisneyFan',
    sellerCountry: 'IT',
    sellerRating: 100,
    sellerReviewCount: 45,
    game: 'lorcana',
    description: 'Mickey Mouse Enchanted rara, condizioni perfette. Scambiata solo in persona finora.',
    imageFront: 'https://picsum.photos/seed/mickeylor/800/1120',
    imageBack: 'https://picsum.photos/seed/mickeylorb/800/1120',
    condition: 'Mint',
    createdByUserId: 'user-disney',
    wantsInReturn: 'Elsa Enchanted o simile rarità',
  },
  {
    id: 'sc-6',
    numericId: 6,
    title: 'Mox Ruby Beta',
    image: 'https://picsum.photos/seed/moxruby/400/560',
    seller: 'VintageMTG',
    sellerCountry: 'IT',
    sellerRating: 96,
    sellerReviewCount: 88,
    game: 'mtg',
    description: 'Mox Ruby Beta, condizioni SP. Un must per ogni collezionista Old School.',
    imageFront: 'https://picsum.photos/seed/moxruby/800/1120',
    imageBack: 'https://picsum.photos/seed/moxrubyb/800/1120',
    condition: 'Slightly Played',
    createdByUserId: 'user-vintage',
    wantsInReturn: 'Mox Jet Beta + differenza',
  },
  {
    id: 'sc-7',
    numericId: 7,
    title: 'Pikachu Illustrator',
    image: 'https://picsum.photos/seed/pikaill/400/560',
    seller: 'PikaMaster',
    sellerCountry: 'IT',
    sellerRating: 99,
    sellerReviewCount: 300,
    game: 'pokemon',
    description: 'Pikachu Illustrator promo card. Riproduzione fedele, non originale (chiarito per onestà).',
    imageFront: 'https://picsum.photos/seed/pikaill/800/1120',
    imageBack: 'https://picsum.photos/seed/pikaillb/800/1120',
    condition: 'Near Mint',
    createdByUserId: 'user-pika',
    wantsInReturn: 'Carte Pokemon vintage bundle',
  },
  {
    id: 'sc-8',
    numericId: 8,
    title: 'Gol D. Roger SP OP-01',
    image: 'https://picsum.photos/seed/rogerop/400/560',
    seller: 'PirateKing',
    sellerCountry: 'IT',
    sellerRating: 94,
    sellerReviewCount: 12,
    game: 'op',
    description: 'Gol D. Roger SP dalla prima serie OP-01. Angolo leggermente toccato, vedi foto.',
    imageFront: 'https://picsum.photos/seed/rogerop/800/1120',
    imageBack: 'https://picsum.photos/seed/rogeropb/800/1120',
    condition: 'Lightly Played',
    createdByUserId: 'user-roger',
    wantsInReturn: 'Whitebeard SP o Ace SP',
  },
];
